version: "3.8"

services: 
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    restart: always
    env_file:
      - ./db.env
    ports:
      - "1433:1433"
    volumes:
      - ./mssqldata:/var/opt/mssql/data:rw